# perspective model for D435i
#==============#
# Camera Model #
#==============#
Camera.name: "Intel realsense D435i"
Camera.setup: "stereo"
Camera.model: "perspective"

Camera.fps: 30.0
Camera.cols: 848
Camera.rows: 480
Camera.fx: 440
Camera.fy: 440
Camera.cx: 424
Camera.cy: 240

Camera.k1: 0.0
Camera.k2: 0.0
Camera.p1: 0.0
Camera.p2: 0.0
Camera.k3: 0.0

Camera.color_order: "RGB"
Camera.focal_x_baseline: 22.0
# 0.05[m]
#================#
# ORB Parameters #
#================#

Feature.max_num_keypoints: 2000
Feature.scale_factor: 1.2
Feature.num_levels: 8
Feature.ini_fast_threshold: 20
Feature.min_fast_threshold: 7
Feature.mask_rectangles:
