# transform of camera 
#Init.transform: [ -18566.7, -93958.5, 44.7]
Init.transform: [ 0.0, 0.0, 0.0]
# normal vector of camera
#Init.normal: [ 1.0, -0.45, 0.0]
Init.normal: [ 1.0, 0.0, 0.0]
# upper vector of camera
Init.upper: [ 0, 0, 1]
# scale
Init.scale: 1.15

Iris.scale_gain: 80.00
Iris.smooth_gain: 0.0
Iris.latitude_gain: 5.0
Iris.altitude_gain: 0.0

Iris.distance_min: 2.0
Iris.distance_max: 5.0

Iris.iteration: 5
Iris.converge_translation: 0.05
Iris.converge_rotation: 0.001

# Map Parameter
Map.voxel_grid_leaf: 0.800
Map.submap_grid_leaf: 80
Map.normal_search_leaf: 0.6
