# Equirectangular model for RICOH THETA S
#==============#
# Camera Model #
#==============#
Camera.name: "Theta S"
Camera.setup: "monocular"
Camera.model: "equirectangular"

Camera.fps: 30.0
Camera.cols: 1280
Camera.rows: 640

Camera.k1: 0.0
Camera.k2: 0.0
Camera.p1: 0.0
Camera.p2: 0.0
Camera.k3: 0.0


Camera.color_order: "RGB"

#================#
# ORB Parameters #
#================#

Feature.max_num_keypoints: 2000
Feature.scale_factor: 1.2
Feature.num_levels: 8
Feature.ini_fast_threshold: 20
Feature.min_fast_threshold: 7
Feature.mask_rectangles:
# for hongo_theta 20210126 
  - [0.0, 0.140, 0.3125, 1.0]
  - [0.140, 0.3515, 0.578, 1.0]
  - [0.3515, 1.0, 0.828, 1.0]
  - [0.9375, 1.0, 0.468, 1.0]
