# ZED2
#==============#
# Camera Model #
#==============#
Camera.name: "ZED2"
Camera.setup: "stereo"
Camera.model: "perspective"

Camera.fps: 10.0
Camera.cols: 1280
Camera.rows: 720

Camera.fx: 530.4
Camera.fy: 530.4
Camera.cx: 635.5
Camera.cy: 355.5

Camera.k1: 0.0
Camera.k2: 0.0
Camera.p1: 0.0
Camera.p2: 0.0
Camera.k3: 0.0

Camera.color_order: "BGR"
Camera.focal_x_baseline: 63.648

#================#
# ORB Parameters #
#================#
Feature.max_num_keypoints: 2000
Feature.scale_factor: 1.2
Feature.num_levels: 8
Feature.ini_fast_threshold: 20
Feature.min_fast_threshold: 7
Feature.mask_rectangles:
  - [0.25, 1.0, 0.82, 1.0]
